version: '3'

services:
  db:
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - "27018:27017"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - WS_SERVER_PORT=4000
      - API_SERVER_PORT=3000
    ports:
      - "4000:${WS_SERVER_PORT}"
      - "3000:${API_SERVER_PORT}"
    links:
      - db
  botbrain:
    build:
      context: ./botbrain
      dockerfile: Dockerfile
    environment:
      - BOT_PORT=3003
    ports:
      - "3003:${BOT_SERVER_PORT}"
    links:
      - db
      - server
  ui:
    build:
      context: ./foyer
      dockerfile: Dockerfile
    environment:
      - VUE_APP_WS_HOST="${SOCKET_DOMAIN}"
      - VUE_APP_API_HOST="${API_DOMAIN}"
      - VUE_APP_LS_PREFIX="CMBAN_"
    ports:
      - "8080:80"
    links:
      - server
