version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  ui:
    build:
      context: ./foyer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - server
