version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
  environment:
      - WS_SERVER_PORT=3001
    ports:
      - "3001:${WS_SERVER_PORT}"
  ui:
    build:
      context: ./foyer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - server
