version: '3'

networks:
  callmebyanyname-net:

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      callmebyanyname-net:
        aliases:
          - server
  ui:
    build:
      context: ./foyer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      callmebyanyname-net:
        aliases:
          - ui
