version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - db
  ui:
    build:
      context: ./foyer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - server
