version: '3'

services:
  db:
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - "27017:27017"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - WS_SERVER_PORT=4000
      - API_SERVER_PORT=3001
      - MONGO_HOST=db
      - MONGO_DB=cbman-1
      - MONGO_PORT=27017
    ports:
      - "4000:4000"
      - "3001:3001"
    links:
      - db
  botbrain:
    build:
      context: ./botbrain
      dockerfile: Dockerfile
    environment:
      - PORT=3003
      - MONGO_DB=cbman-1
      - MONGO_HOST=db
      - MONGO_PORT=27017
    ports:
      - "3003:3003"
    links:
      - db
      - server
  ui:
    build:
      context: ./foyer
      dockerfile: Dockerfile
    environment:
      - VUE_APP_WS_HOST="callmesocket.lislis.xyz"
      - VUE_APP_API_HOST="callmeserver.lislis.xyz"
      - VUE_APP_LS_PREFIX="CMBAN_"
    ports:
      - "8080:80"
    links:
      - server
