name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Server lint
      run: |
        cd server
        yarn install
        yarn lint
    - name: Botbrain lint
      run: |
        cd botbrain
        yarn install
        yarn lint
    - name: Runner lint
      run: |
        cd runner
        yarn install
        yarn lint
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Lint
        run: |
          cd ui
          yarn install
          yarn lint
      - name: Test
        run: |
          cd ui
          yarn install
          yarn test:unit
